#!/usr/bin/env ruby

original_cwd = Dir.pwd

web_dir = File.join(original_cwd, 'web')
begin
  Dir.chdir(web_dir) do
    if Dir.exist?(File.join(web_dir, '.modman'))
      # Deploy modman
      puts "Deploying 'src' dir"
      system("modman deploy src")
    else
      # Initialize modman in the public web root
      puts "Installing 'src' dir"
      system("modman init")
      system("modman link ../src/")
    end
  end
rescue
  puts "I can't find the 'web/' dir. Have you ran 'composer update' yet?"
end
