#!/usr/bin/env ruby

original_cwd = Dir.pwd

puts "Installing 'src' dir"

# Initialize modman in the public web root
web_dir = File.join(original_cwd, 'web')
Dir.chdir(web_dir)
system('modman init') unless File.directory?('.modman')

system("modman link ../src/")
